// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gchyweianhphhhndmgoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjaHl3ZWlhbmhwaGhobmRtZ29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzQwMTAsImV4cCI6MjA1ODcxMDAxMH0.9AaUz_jl5GUJlltOz3S__o7-a_8TvQhMNliOGfL5Ezs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);