// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csuslcygdoefhkrqaoyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdXNsY3lnZG9lZmhrcnFhb3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDE3MDYsImV4cCI6MjA1ODAxNzcwNn0.qjgLk9KajeiRSVNVhindcViM_j6GqnVzNzMCh9JutqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);